name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7
  - plyfile=0.8.1
  - python=3.8
  - pip
  # - pytorch=1.13.0
  # - torchaudio=0.13.0
  # - torchvision=0.14.0
  - tqdm
  # - pip:
  #   - submodules/diff-gaussian-rasterization
  #   - submodules/simple-knn